### PR TITLE
Created MTB accelerometers tests

### PR DESCRIPTION
**Pull request by nunoguedelha**
PLEASE, DO NOT MERGE YET.

The new plugin `AccelerometersReading` runs a diagnosis on the MTB inertial sensors (for now only the accelerometers). A single run of this plugin will perform the check for a single part of a robot (a leg, an arm, the torso, ...). The main mandatory parameters are:
- robot name (ex: "icub") as used by YARP to name the robot ports
- part ("left_leg", "right_arm", ...)
- bus type (Ethernet or Can. The data parsing depends on this parameter)
- mtbList: list of sensors to read

There are some optional input parameters like:
- sampleTime (delay between 2 port read-outs)
- dataDumpFile

The data can be either read from a yard port (online test) or from a file previously generated by the data dumper (offline).

**Checks performed:**
- the sensor data are accessible (ports where sensor data is published can be opened)
- there are no sensor output errors (0xFFFFFFFF)
- data consistency (*)

(*):
The robot is assumed to be still or moving very slowly, such that only the gravity is measured by the accelerometers. The checks performed for each sensor are:
- First, a reference acceleration (gravity) vector is set through an averaged measure.
- then, while the robot part can be actuated by an external controller, we measure the angle of the measured gravity w.r.t. the reference.
- gravity vector is also compared with the "expected" measurements, computed from the model and joint positions measurements.
  <a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/robotology/icub-tests/pull/21%23issuecomment-217957408%22%2C%20%22https%3A//github.com/robotology/icub-tests/pull/21%23issuecomment-217958440%22%2C%20%22https%3A//github.com/robotology/icub-tests/pull/21%23issuecomment-218083207%22%2C%20%22https%3A//github.com/robotology/icub-tests/pull/21%23issuecomment-218165963%22%2C%20%22https%3A//github.com/robotology/icub-tests/pull/21%23issuecomment-218227214%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/robotology/icub-tests/pull/21%23issuecomment-217957408%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22What%20is%20the%20purpose%20of%20having%20two%20different%20parsers%2C%20MTBsensorParserEth%20and%20MTBsensorParserCan%3F%20%22%2C%20%22created_at%22%3A%20%222016-05-09T19%3A01%3A51Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/2869969%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/randaz81%22%7D%7D%2C%20%7B%22body%22%3A%20%22The%20complexity%20of%20this%20test%20seems%20too%20big%20respect%20to%20usual%20%5C%22check-just-a-single-failure-case%5C%22%20philosophy%20%20adopted%20in%20this%20repo.%20Are%20you%20sure%20that%20your%20test%20cannot%20be%20splitted%20into%20multiple%2C%20simpler%20tests%3F%22%2C%20%22created_at%22%3A%20%222016-05-09T19%3A05%3A16Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/2869969%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/randaz81%22%7D%7D%2C%20%7B%22body%22%3A%20%22%40randaz81%20yes%2C%20we%20are%20still%20working%20on%20it%20%3A%20%29%20%5Cr%5Cn%5Cr%5CnFor%20the%20eth/can%20difference%2C%20that%20is%20due%20to%20a%20difference%20between%20how%20the%20%60CanBusInertialMTB%60%20and%20%60embObjInertials%60%20drivers%20publish%20data.%20My%20proposal%20in%20https%3A//github.com/robotology/yarp/issues/747%20was%20done%20explicitly%20to%20address%20that%2C%20by%20my%20moving%20this%20logic%20to%20a%20wrapper%2C%20that%20communicates%20with%20the%20devices%20with%20a%20clearly%20specified%20C%2B%2B%20interface.%20As%20already%20agreed%20by%20email%2C%20we%20can%20discuss%20about%20it%20when%20we%20are%20back%20in%20Genoa.%20%22%2C%20%22created_at%22%3A%20%222016-05-10T07%3A48%3A03Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1857049%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/traversaro%22%7D%7D%2C%20%7B%22body%22%3A%20%22First%20of%20all%2C%20i%20think%20is%20very%20important%20unify%20the%20output%20of%20%60CanBusInertialMTB%60%20and%20%60embObjInertials%60%2C%20but%20currently%20I%20haven%27t%20clear%20ideas..%20%3A%28%20I%20need%20%20to%20read%20up%20a%20bit%20more...%5Cr%5Cn%5Cr%5CnSecond%2C%20I%20agree%20with%20%40randaz81%20that%20a%20test%20should%20verify%20a%20single%20behaviour%20%2C%20but%20now%20this%20application%20is%20in%20%5C%22work%20in%20progress%5C%22%2C%20therefore%20we%20can%20discuss%20together%20how%20to%20split%20this%20test%20application%20in%20more%20simples%20when%20it%20will%20be%20stable%5Cr%5Cn%5Cr%5CnUsually%2C%20I%20define%20a%20test%20to%20verify%20the%20hardware%2C%20one%20to%20verify%20the%20communication%20and%20one%20to%20verify%20data%20consistency.%5Cr%5CnIn%20this%20way%3A%5Cr%5Cn%20%20-%20production%20guys%20can%20check%20hardware%20before%20release%20a%20robot.%20%5Cr%5Cn%20%20-%20we%20can%20check%20firmware%20behaviour%2C%20running%20only%20data%20consistency%20test.%5Cr%5Cn%5Cr%5CnMoreover%20if%20we%20need%20to%20check%20inertial%20sensor%20overall%2C%20it%20is%20possible%20to%20create%20a%20test%20suit%20where%20get%20together%20%20%5C%22small%20tests%5C%22.%5Cr%5Cn%20%22%2C%20%22created_at%22%3A%20%222016-05-10T14%3A00%3A16Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/4233231%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/valegagge%22%7D%7D%2C%20%7B%22body%22%3A%20%22%40valegagge%20%2C%20I%20understand%20and%20fully%20agree.%20I%20was%20actually%20planning%20to%20use%20an%20input%20parameter%20%28%5C%22subtest%5C%22%29%20as%20a%20subtest%20selector%20%28it%20is%20already%20in%20the%20plugin%20header%2C%20but%20not%20processed%20yet%29.%5Cr%5CnSo%20the%20split%20you%27ve%20mentioned%20would%20be%20done%20through%20the%20test%20suit%2C%20setting%20this%20parameter%20to%20%27hardware%27%20or%20%27dataConsistency%27%20for%20instance.%20This%20way%2C%20we%20can%20get%20a%20single%20behaviour%20depending%20on%20the%20%5C%22subtest%5C%22%20parameter%20and%20still%20keep%20a%20single%20plugin.%20Having%20a%20single%20plugin%20has%20advantages%20like%3A%5Cr%5Cn-%20we%20avoid%20duplicating%20code%5Cr%5Cn-%20we%20can%20stack%20subtests%20if%20necessary.%20For%20instance%2C%20you%20might%20want%20to%20test%20data%20consistency%20%28comparing%20accelerometers%20measurements%20with%20expected%20specific%20values%29%2C%20but%20still%20be%20sure%20that%20a%20failure%20is%20not%20due%20to%20a%20random%20hardware%20issue%20setting%20the%20data%20to%20FFFF.%20In%20other%20words%2C%20some%20subtests%20might%20be%20included%20both%20in%20low%20level%20and%20high%20level%20tests.%5Cr%5Cn%5Cr%5CnOn%20top%20of%20that%2C%20some%20part%20of%20the%20complexity%20in%20the%20actual%20version%20of%20the%20plugin%20will%20most%20probably%20be%20transferred%20to%20%60iDynTree%60.%22%2C%20%22created_at%22%3A%20%222016-05-10T17%3A16%3A41Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/6848872%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/nunoguedelha%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%7D'></a>
  <a href='https://www.codereviewhub.com/'></a>
- [ ] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/robotology/icub-tests/pull/21#issuecomment-217957408'>General Comment</a></b>
- <a href='https://github.com/randaz81'></a> What is the purpose of having two different parsers, MTBsensorParserEth and MTBsensorParserCan?
- <a href='https://github.com/randaz81'></a> The complexity of this test seems too big respect to usual "check-just-a-single-failure-case" philosophy  adopted in this repo. Are you sure that your test cannot be splitted into multiple, simpler tests?
- <a href='https://github.com/traversaro'></a> @randaz81 yes, we are still working on it : )
  For the eth/can difference, that is due to a difference between how the `CanBusInertialMTB` and `embObjInertials` drivers publish data. My proposal in https://github.com/robotology/yarp/issues/747 was done explicitly to address that, by my moving this logic to a wrapper, that communicates with the devices with a clearly specified C++ interface. As already agreed by email, we can discuss about it when we are back in Genoa.
- <a href='https://github.com/valegagge'></a> First of all, i think is very important unify the output of `CanBusInertialMTB` and `embObjInertials`, but currently I haven't clear ideas.. :( I need  to read up a bit more...
  Second, I agree with @randaz81 that a test should verify a single behaviour , but now this application is in "work in progress", therefore we can discuss together how to split this test application in more simples when it will be stable
  Usually, I define a test to verify the hardware, one to verify the communication and one to verify data consistency.
  In this way:
- production guys can check hardware before release a robot.
- we can check firmware behaviour, running only data consistency test.
  Moreover if we need to check inertial sensor overall, it is possible to create a test suit where get together  "small tests".
- <a href='https://github.com/nunoguedelha'></a> @valegagge , I understand and fully agree. I was actually planning to use an input parameter ("subtest") as a subtest selector (it is already in the plugin header, but not processed yet).
  So the split you've mentioned would be done through the test suit, setting this parameter to 'hardware' or 'dataConsistency' for instance. This way, we can get a single behaviour depending on the "subtest" parameter and still keep a single plugin. Having a single plugin has advantages like:
- we avoid duplicating code
- we can stack subtests if necessary. For instance, you might want to test data consistency (comparing accelerometers measurements with expected specific values), but still be sure that a failure is not due to a random hardware issue setting the data to FFFF. In other words, some subtests might be included both in low level and high level tests.
  On top of that, some part of the complexity in the actual version of the plugin will most probably be transferred to `iDynTree`.

<a href='https://www.codereviewhub.com/robotology/icub-tests/pull/21?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/robotology/icub-tests/pull/21?approve=1'></a>&nbsp;<a href='https://github.com/robotology/icub-tests/pull/21'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by pattacini** [comment]
This pull request is now managed with CodeReviewHub. <a href='https://github.com/robotology/icub-tests/pull/21'>Refresh</a>.<a href='#crh-update-none'></a>

**Comment by randaz81** [comment]
What is the purpose of having two different parsers, MTBsensorParserEth and MTBsensorParserCan?

**Comment by randaz81** [comment]
The complexity of this test seems too big respect to usual "check-just-a-single-failure-case" philosophy  adopted in this repo. Are you sure that your test cannot be splitted into multiple, simpler tests?

**Comment by traversaro** [comment]
@randaz81 yes, we are still working on it : ) 

For the eth/can difference, that is due to a difference between how the `CanBusInertialMTB` and `embObjInertials` drivers publish data. My proposal in https://github.com/robotology/yarp/issues/747 was done explicitly to address that, by my moving this logic to a wrapper, that communicates with the devices with a clearly specified C++ interface. As already agreed by email, we can discuss about it when we are back in Genoa.

**Comment by valegagge** [comment]
First of all, i think is very important unify the output of `CanBusInertialMTB` and `embObjInertials`, but currently I haven't clear ideas.. :( I need  to read up a bit more...

Second, I agree with @randaz81 that a test should verify a single behaviour , but now this application is in "work in progress", therefore we can discuss together how to split this test application in more simples when it will be stable

Usually, I define a test to verify the hardware, one to verify the communication and one to verify data consistency.
In this way:
  - production guys can check hardware before release a robot. 
  - we can check firmware behaviour, running only data consistency test.

Moreover if we need to check inertial sensor overall, it is possible to create a test suit where get together  "small tests".

**Comment by nunoguedelha** [comment]
@valegagge , I understand and fully agree. I was actually planning to use an input parameter ("subtest") as a subtest selector (it is already in the plugin header, but not processed yet).
So the split you've mentioned would be done through the test suit, setting this parameter to 'hardware' or 'dataConsistency' for instance. This way, we can get a single behaviour depending on the "subtest" parameter and still keep a single plugin. Having a single plugin has advantages like:
- we avoid duplicating code
- we can stack subtests if necessary. For instance, you might want to test data consistency (comparing accelerometers measurements with expected specific values), but still be sure that a failure is not due to a random hardware issue setting the data to FFFF. In other words, some subtests might be included both in low level and high level tests.

On top of that, some part of the complexity in the actual version of the plugin will most probably be transferred to `iDynTree`.

**Comment by pattacini** [comment]
It was open since an age, closing.
We can open it again when/if requested.

**Pull request closed without merging**
