### PR TITLE
improve camera test

### PR DESCRIPTION
**Pull request by lornat75**
renamed variables and parameters for clearer understanding, modified expected rate to match simulator, increased slightly tolerance

### CODE REVIEW

**Comment by lornat75** [comment]
@traversaro I just wanted to bring your attention to this so you are aware of these changes, I would like to merge this pr.

**Comment by traversaro** [comment]
:+1: ok for me. 
Apparently we should solve manually some conflicts. I can do that if you want @lornat75 .

**Comment by lornat75** [comment]
Yes please.

**Comment by traversaro** [comment]
Rebased changes in https://github.com/robotology/icub-tests/commit/cf3fbf82510e575b15ed913df710c61b3e4e1454 (I have to open a new PR because I don't have write access to the lornat75 fork.

**Pull request closed without merging**
